name: lightweight
description: Training App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  simple_animations: ^4.1.0
  supercharged: ^2.1.1
  pin_code_fields: ^7.4.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.1.11
  build_web_compilers: ^3.2.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  fonts:
    - family: HOBIES
      fonts:
        - asset: assets/fonts/HOBIES.ttf
    - family: ROYALMOSCOW
      fonts:
        - asset: assets/fonts/ROYALMOSCOW.ttf

  assets:
    - assets/images/
  uses-material-design: true
