import 'Exercise.dart';

const List<Exercise> chestWorkout = [
  const Exercise(
    eid: '1',
    name: 'Push Up',
    type: 'Chest',
    description: 'A basic bodyweight exercise to train the chest, shoulders, and triceps.',
    sets: 3,
    repetitions: 15,
    intensity: 'Medium',
    prevImage: 'https://mensfitness.co.uk/wp-content/uploads/sites/2/2022/03/DB-incline-bench.jpg',
    image: 'https://i.pinimg.com/originals/b6/28/0f/b6280fbba2b4e7155a4a1901dfeebc9d.gif',
  ),
  const Exercise(
    eid: '2',
    name: 'Bench Press',
    type: 'Chest',
    description: 'A compound movement to target the chest using a barbell or dumbbells.',
    sets: 4,
    repetitions: 10,
    intensity: 'High',
    prevImage: 'https://mensfitness.co.uk/wp-content/uploads/sites/2/2022/03/DB-incline-bench.jpg',
    image: 'https://i.pinimg.com/originals/b6/28/0f/b6280fbba2b4e7155a4a1901dfeebc9d.gif',
  ),
  const Exercise(
    eid: '3',
    name: 'Chest Fly',
    type: 'Chest',
    description: 'An isolation exercise to train the chest muscles using dumbbells.',
    sets: 3,
    repetitions: 12,
    intensity: 'Low',
    prevImage: 'https://mensfitness.co.uk/wp-content/uploads/sites/2/2022/03/DB-incline-bench.jpg',
    image: 'https://i.pinimg.com/originals/b6/28/0f/b6280fbba2b4e7155a4a1901dfeebc9d.gif',
  ),
  const Exercise(
    eid: '3',
    name: 'Chest Fly',
    type: 'Chest',
    description: 'An isolation exercise to train the chest muscles using dumbbells.',
    sets: 3,
    repetitions: 12,
    intensity: 'Low',
    prevImage: 'https://mensfitness.co.uk/wp-content/uploads/sites/2/2022/03/DB-incline-bench.jpg',
    image: 'https://i.pinimg.com/originals/b6/28/0f/b6280fbba2b4e7155a4a1901dfeebc9d.gif',
  ),
  const Exercise(
    eid: '3',
    name: 'Chest Fly',
    type: 'Chest',
    description: 'An isolation exercise to train the chest muscles using dumbbells.',
    sets: 3,
    repetitions: 12,
    intensity: 'Low',
    prevImage: 'https://mensfitness.co.uk/wp-content/uploads/sites/2/2022/03/DB-incline-bench.jpg',
    image: 'https://i.pinimg.com/originals/b6/28/0f/b6280fbba2b4e7155a4a1901dfeebc9d.gif',
  ),
  const Exercise(
    eid: '3',
    name: 'Chest Fly',
    type: 'Chest',
    description: 'An isolation exercise to train the chest muscles using dumbbells.',
    sets: 3,
    repetitions: 12,
    intensity: 'Low',
    prevImage: 'https://mensfitness.co.uk/wp-content/uploads/sites/2/2022/03/DB-incline-bench.jpg',
    image: 'https://i.pinimg.com/originals/b6/28/0f/b6280fbba2b4e7155a4a1901dfeebc9d.gif',
  ),
];
