import 'Exercise.dart';

const List<Exercise> chestWorkout = [
  const Exercise(
    eid: '1',
    name: 'Incline Presses',
    type: 'Chest',
    description: 'Strength exercise that targets the upper chest, and with secondary concentration on the shoulders and triceps, the degree of the incline bench should be around 30deg.',
    sets: 3,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/1.gif',
  ),
  const Exercise(
    eid: '2',
    name: 'Bench Press',
    type: 'Chest',
    description: 'This exercise targets the middle chest, this is one of the fundemental exercises in both bodybuilding and powerlifting.',
    sets: 4,
    repetitions: 12,
    intensity: 'High',
    image: 'assets/images/exercises/2.gif',
  ),
  const Exercise(
    eid: '3',
    name: 'Close-Grib Bench Press',
    type: 'Chest',
    description: 'An isolation exercise to train the chest muscles using dumbbells.',
    sets: 3,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/3.gif',
  ),
  const Exercise(
    eid: '4',
    name: 'Decline Bench Press',
    type: 'Chest',
    description: 'An isolation exercise to train the chest muscles using dumbbells.',
    sets: 3,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/4.gif',
  ),
  const Exercise(
    eid: '5',
    name: 'Push ups',
    type: 'Chest',
    description: 'One of the classical workouts, that targets mainly the whole chest muscle, with a secondary focus on the triceps.',
    sets: 5,
    repetitions: 20,
    intensity: 'Low',
    image: 'assets/images/exercises/5.gif',
  ),
  const Exercise(
    eid: '6',
    name: 'Parallel bar dips',
    type: 'Chest',
    description: 'A bodyweight exercises, and could also done with adding additional weight to the body\'s mass, it is mainly targetting the lower chest with a secondary focus on the triceps',
    sets: 3,
    repetitions: 10,
    intensity: 'High',
    image: 'assets/images/exercises/6.gif',
  ),
  const Exercise(
    eid: '7',
    name: 'Dumbbell Presses',
    type: 'Chest',
    description: 'The dumbbell press, a classic upper-body strengthening technique, focuses on enhancing the chest muscles. While the primary emphasis is on the chest, it also provides secondary benefits by involving the front deltoids and triceps. This exercise acts as an alternative to the barbell bench press, offering unique advantages due to its utilization of individual dumbbells.',
    sets: 4,
    repetitions: 12,
    intensity: 'High',
    image: 'assets/images/exercises/7.gif',
  ),
  const Exercise(
    eid: '8',
    name: 'Dumbbell Flys',
    type: 'Chest',
    description: 'The dumbbell fly exercise primarily focuses on the sternal heads of the pectoralis major muscles located in the chest. Additionally, it also engages and strengthens various other muscle groups including the triceps, deltoids, biceps, wrist flexors, and brachialis muscles. This exercise is highly effective for achieving well-defined pectoral muscles and is recommended for those aiming for a more sculpted and ripped chest appearance.',
    sets: 4,
    repetitions: 15,
    intensity: 'Medium',
    image: 'assets/images/exercises/8.gif',
  ),
  const Exercise(
    eid: '9',
    name: 'Incline Dumbbell Presses',
    type: 'Chest',
    description: 'The incline dumbbell press is a weightlifting exercise designed to enhance strength. It focuses on the upper pectoral muscles while also engaging the shoulders and triceps. This exercise is carried out on an inclined bench positioned at a 30-45 degree angle, utilizing a dumbbell in each hand.',
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/9.gif',
  ),

  const Exercise(
    eid: '10',
    name: 'Incline Dumbbell Flys',
    type: 'Chest',
    description: 'The incline dumbbell fly is a concentrated workout aimed at the challenging-to-build upper chest muscles. Achieving a balanced development of pectoral muscles involves applying distinct weights from different angles. By performing horizontal adduction exercises, the muscle fibers are engaged, leading to both activation and growth of the chest muscles.',
    sets: 4,
    repetitions: 15,
    intensity: 'Medium',
    image: 'assets/images/exercises/10.gif',
  ),
  const Exercise(
    eid: '13',
    name: 'Dumbbell Pull-Over',
    type: 'Chest',
    description: "The dumbbell pullover is a strength-focused workout that engages upper body muscles such as the chest, back, and shoulders. This exercise is performed by lying on a flat or slightly inclined bench while holding a dumbbell with both hands positioned above the chest",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/13.gif',
  ),
];

const List<Exercise> tricepsWorkout = [
  Exercise(
    eid: '14',
    name: 'Push Downs',
    type: 'Triceps',
    description: "The triceps push-down is a commonly performed strength training exercise aimed at working the triceps muscles located on the back of the upper arms. This exercise is fundamental for both developing triceps strength and defining the muscles. It is typically carried out using a cable machine available in most gym settings",
    sets: 4,
    repetitions: 20,
    intensity: 'Medium',
    image: 'assets/images/exercises/14.gif',
  ),
  Exercise(
    eid: '15',
    name: 'Reverse Pushdowns',
    type: 'Triceps',
    description: "The reverse-grip pushdown is a specialized exercise that focuses on the triceps muscles without involving other muscle groups or joints. Using an underhand grip puts extra emphasis on the medial head of the triceps. Including this exercise regularly in your routine, if not every workout, is crucial for well-rounded triceps development due to its targeted effect on a specific triceps head.",
    sets: 4,
    repetitions: 15,
    intensity: 'Medium',
    image: 'assets/images/exercises/15.gif',
  ),
  Exercise(
    eid: '16',
    name: 'Triceps Extension',
    type: 'Triceps',
    description: "The dumbbell triceps extension is an isolation exercise primarily aimed at promoting triceps hypertrophy. By executing this movement, all three heads of the triceps are engaged, leading to comprehensive strengthening and development of the entire triceps muscle group.",
    sets: 3,
    repetitions: 20,
    intensity: 'Medium',
    image: 'assets/images/exercises/16.gif',
  ),
  Exercise(
    eid: '17',
    name: 'Dumbbell Triceps Extension',
    type: 'Triceps',
    description: "The dumbbell triceps extension is categorized as an isolation exercise, focusing on enhancing triceps hypertrophy. Through this motion, all three triceps heads are activated, ensuring a comprehensive strengthening and development of the entire triceps muscle group.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/17.gif',
  ),
  Exercise(
    eid: '18',
    name: 'EZ BAR EXTENSION',
    type: 'Triceps',
    description: "The EZ bar lying close grip triceps extension behind the head is a compound exercise that targets the triceps muscles. It involves using an EZ bar and lying on a bench while lowering the bar behind the head and then extending the arms to lift the bar back up. ",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/18.gif',
  ),
  Exercise(
    eid: '19',
    name: 'Dumbbell Kickback',
    type: 'Triceps',
    description: "The dumbbell kickback is a well-known strength training exercise designed to focus on the triceps muscles located at the rear of the upper arms. This exercise plays a role in enhancing and shaping the triceps, thereby contributing to both arm strength and visual appeal.",
    sets: 4,
    repetitions: 20,
    intensity: 'Medium',
    image: 'assets/images/exercises/19.gif',
  ),
  Exercise(
    eid: '20',
    name: 'Triceps Dips',
    type: 'Triceps',
    description: "Triceps dips performed on the floor are classified as compound exercises due to their engagement of several muscle groups at the same time. While primarily focusing on the triceps, this bodyweight exercise also effectively stimulates the chest and the anterior (front) shoulder muscles.",
    sets: 4,
    repetitions: 15,
    intensity: 'Medium',
    image: 'assets/images/exercises/20.gif',
  ),
];



const List<Exercise> backWorkout = [
  Exercise(
    eid: '21',
    name: 'Reverse Chin Ups',
    type: 'Back',
    description: "Chin-ups are a foundational multi-joint compound exercise frequently integrated into calisthenic and athletic training regimens. This exercise involves utilizing the body's weight as resistance and is commonly employed to target the back and bicep muscles in such programs.",
    sets: 4,
    repetitions: 12,
    intensity: 'Low',
    image: 'assets/images/exercises/21.gif',
  ),
  Exercise(
    eid: '22',
    name: 'Back Pull-Downs',
    type: 'Back',
    description: "Back Lat pulldowns are a popular strength training exercise that targets the muscles of the upper back, particularly the latissimus dorsi (lats), as well as the biceps and other supporting muscles. This exercise is often performed using a pulldown machine in the gym, but similar movements can be replicated using resistance bands or other equipment, it differs from the back pull downs that it focus more on the middle of the back.",
    sets: 4,
    repetitions: 20,
    intensity: "Low",
    image: 'assets/images/exercises/22.gif',
  ),
  Exercise(
    eid: '23',
    name: 'Lat Pull-Downs',
    type: 'Back',
    description: "Lat pulldowns are a popular strength training exercise that targets the muscles of the upper back, particularly the latissimus dorsi (lats), as well as the biceps and other supporting muscles. This exercise is often performed using a pulldown machine in the gym, but similar movements can be replicated using resistance bands or other equipment.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/23.gif',
  ),
  Exercise(
    eid: '24',
    name: 'Close Grip Lat Pull-Downs',
    type: 'Back',
    description: "",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/24.gif',
  ),
  Exercise(
    eid: '25',
    name: 'Straight Arm Lat Pull-Downs',
    type: 'Back',
    description: "Straight Arm Lat Pull-Downs are an effective isolation exercise targeting the latissimus dorsi muscles, which are the large muscles on the sides of your back. The movement involves standing in front of a cable pulley machine, grabbing a bar with an overhand grip, and then pulling the bar down to your waist or thighs while keeping your arms straight. This exercise differs from the regular lat pull-down because the arms remain straight throughout, placing more emphasis on the lats and less on the biceps. Incorporating Straight Arm Lat Pull-Downs into your routine can help develop a wider back, improving the V-taper appearance, and also strengthening the muscles involved in actions such as pulling and reaching.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/25.gif',
  ),
  Exercise(
    eid: '26',
    name: 'Seated Rows',
    type: 'Back',
    description: "Seated Rows are a compound exercise that primarily targets the muscles of the middle back, including the rhomboids, trapezius, and the latissimus dorsi. They also engage the biceps, forearms, and the muscles around the shoulder blades. To perform this exercise, one typically sits on a row machine with a V-bar or wide grip handle, plants their feet against footrests, and leans slightly forward from the waist. The movement involves pulling the handle towards the torso, squeezing the shoulder blades together at the peak contraction, and then slowly returning the weight to the starting position. This exercise is essential for developing a strong and thick back and contributes to better posture and enhanced pulling strength. Regularly incorporating seated rows into a training regimen can aid in creating balance with chest exercises, preventing muscle imbalances and postural issues.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/26.gif',
  ),
  Exercise(
    eid: '27',
    name: 'One Arm Rows',
    type: 'Back',
    description: "One Arm Rows, often referred to as Single Arm Dumbbell Rows, are a compound exercise designed to target the muscles of the upper and middle back, especially the latissimus dorsi. Secondary muscles worked include the biceps, brachialis, and brachioradialis, with stabilization from the core muscles. To perform this exercise, one typically uses a flat bench and a dumbbell. Placing one knee and the same-side hand on the bench, while the other foot remains on the ground, you maintain a neutral spine, letting the opposite arm hang down holding the dumbbell. The movement involves pulling the dumbbell upwards towards the hip, driving the elbow back and squeezing the shoulder blade toward the spine, before lowering it back to the starting position. One Arm Rows are excellent for isolating one side of the back, ensuring even development and strength. They also promote enhanced scapular mobility and muscle control, aiding in better shoulder health and posture.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/27.gif',
  ),
  Exercise(
    eid: '28',
    name: 'Bent Over Rows',
    type: 'Back',
    description: "Bent Over Rows are a compound back exercise that targets the latissimus dorsi, rhomboids, and traps. Using a barbell or dumbbells, you bend at the waist with a slight bend in the knees, maintaining a neutral spine. The weight is then lifted towards the lower rib cage by retracting the shoulder blades and driving the elbows back. This exercise is key for a strong, muscular back and improved pulling power.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/28.gif',
  ),

  Exercise(
    eid: '29',
    name: 'T-Bar Rows',
    type: 'Back',
    description: "T-Bar Rows are a compound back exercise that utilizes a T-bar row machine or a landmine attachment. Standing over the bar, you grip the handles and lift the weight by squeezing the shoulder blades together and driving the elbows toward the ceiling. It primarily targets the middle back, lats, and traps, offering an excellent blend of strength and muscle-building benefits for the upper body.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/29.gif',
  ),

  Exercise(
    eid: '30',
    name: 'Dead Lift',
    type: 'Back',
    description: "The Deadlift is a fundamental compound exercise that engages multiple muscle groups, including the glutes, hamstrings, lower and upper back, traps, and forearms. Starting with a barbell on the ground, you grip it with both hands and lift by driving through the heels, extending the hips and knees, and maintaining a neutral spine. The movement culminates in an upright stance. Deadlifts are paramount for building overall strength, enhancing muscle mass, and improving functional fitness.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/30.gif',
  ),

  Exercise(
    eid: '31',
    name: 'Upright Row',
    type: 'Back',
    description: "Upright Rows are a compound exercise focusing on the deltoids, traps, and the upper portion of the biceps. Using a barbell or dumbbells, you grip the weight with hands close together and pull it vertically close to the body, leading with the elbows. The movement concludes when the elbows reach shoulder height or slightly above. Upright rows help in defining the shoulders and increasing upper body strength, but caution is needed as they can sometimes strain the rotator cuff if not performed correctly.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/31.gif',
  ),
];


const List<Exercise> bicepsWorkout = [
  Exercise(
    eid: '32',
    name: 'Curls',
    type: 'Biceps',
    description: "Curls, commonly known as bicep curls, are an isolation exercise primarily targeting the biceps brachii muscle, located in the upper arm. Using dumbbells, barbells, or resistance bands, you start with arms fully extended and then flex the elbows to curl the weight towards the shoulders. The controlled lowering phase also engages the biceps. Curls are fundamental for building arm strength and enhancing the size and definition of the biceps.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/32.gif',
  ),
  Exercise(
    eid: '33',
    name: 'Concentration Curls',
    type: 'Biceps',
    description: "Concentration Curls are an isolation exercise honed in on the biceps brachii. Typically done with a dumbbell, the exercise involves sitting on a bench with legs spread and an arm resting against an inner thigh. Holding the weight, you curl it towards your shoulder, ensuring the upper arm remains stationary. The positioning isolates the biceps and minimizes the involvement of other muscles. This focused contraction leads to increased muscle activation, making it an excellent choice for detailed bicep development and peak enhancement.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/33.gif',
  ),
  Exercise(
    eid: '34',
    name: 'Hammer Curls',
    type: 'Biceps',
    description: "Hammer Curls are a variation of the traditional bicep curl, primarily targeting the biceps brachii and the brachialis, a muscle located beneath the biceps. Using dumbbells, the exercise is performed with a neutral grip, meaning the palms face each other throughout the movement. Starting with arms extended, the weights are curled upwards without rotating the wrists. This grip and motion place additional emphasis on the brachialis and the outer portion of the biceps, leading to a more comprehensive arm development and improved grip strength.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/34.gif',
  ),
  Exercise(
    eid: '35',
    name: 'One Arm Cable Curls',
    type: 'Biceps',
    description: "One Arm Cable Curls use a cable machine to target the biceps. Standing facing the machine, you grip a single handle and curl toward the shoulder. The cable provides constant tension, ensuring the biceps work during both the lifting and lowering phases. This exercise emphasizes individual arm focus, promoting even development.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/35.gif',
  ),
  Exercise(
    eid: '36',
    name: 'Two Arm Seated Curls',
    type: 'Biceps',
    description: "Two Arm Seated Cable Curls utilize a cable machine to hone in on the biceps. While seated, you grip two handles attached to the machine and simultaneously curl both towards your shoulders. The cable provides consistent resistance, maximizing bicep engagement throughout the entire motion.",
    sets: 4,
    repetitions: 12,
    intensity: 'Low',
    image: 'assets/images/exercises/36.gif',
  ),
  Exercise(
    eid: '37',
    name: 'Barbell Curls',
    type: 'Biceps',
    description: "Barbell Curls are a classic exercise targeting the biceps. Holding a barbell with an underhand grip and arms extended, you curl the weight towards your chest. This move effectively engages the entire bicep muscle, promoting strength and mass growth.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/37.gif',
  ),
  Exercise(
    eid: '38',
    name: 'Machine Curls',
    type: 'Biceps',
    description: "Machine Curls use a dedicated curl machine to isolate the biceps. With adjustable resistance and fixed motion, users curl the handles towards them. This equipment ensures proper form, minimizing the risk of injury and providing consistent tension for optimal bicep engagement.",
    sets: 4,
    repetitions: 12,
    intensity: 'Low',
    image: 'assets/images/exercises/38.gif',
  ),
  Exercise(
    eid: '39',
    name: 'Barbell Reverse Curls',
    type: 'Biceps',
    description: "Reverse Curls target the biceps and the brachioradialis in the forearms. Holding a barbell or dumbbells with an overhand grip, you curl the weight towards the chest. This grip variation shifts emphasis to the forearm muscles, aiding in balanced arm development and increased grip strength.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/39.gif',
  ),
];



const List<Exercise> legsWorkout = [
  Exercise(
    eid: '40',
    name: 'Dumbbell Goblet Squat',
    type: 'Legs',
    description: "The Dumbbell Goblet Squat is a compound exercise primarily targeting the quads, glutes, and hamstrings. Holding a dumbbell vertically by one end close to the chest, you squat down, keeping your chest upright and knees tracking over toes. This variation not only strengthens the lower body but also engages the core and upper body for stability, making it a versatile and functional exercise",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/40.gif',
  ),
  Exercise(
    eid: '41',
    name: 'Barbell Squat',
    type: 'Legs',
    description: "The Barbell Squat is a foundational compound exercise that targets the quads, glutes, hamstrings, and lower back. Using a barbell placed on the upper traps, you squat down, pushing your hips back while maintaining a neutral spine. This powerful exercise is key for building lower body strength, muscle mass, and enhancing overall athletic performance.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/41.gif',
  ),
  Exercise(
    eid: '42',
    name: 'Leg Press',
    type: 'Legs',
    description: "The Leg Press is a compound exercise that emphasizes the quads, hamstrings, and glutes. Using a leg press machine, you sit and push a weighted platform away by extending the knees and hips. The controlled, guided motion allows for heavy loads, making it a staple for building leg strength and muscle volume.",
    sets: 4,
    repetitions: 15,
    intensity: 'Medium',
    image: 'assets/images/exercises/42.gif',
  ),
  Exercise(
    eid: '43',
    name: 'Hack Squat',
    type: 'Legs',
    description: "Hack Squats, performed on a hack squat machine, target the quads, glutes, and hamstrings. The user leans back against a padded support, places the shoulders under the pads, and squats down while pushing against a fixed platform. The machine provides stability and focus, allowing for a concentrated effort on the targeted leg muscles.",
    sets: 4,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/43.gif',
  ),
  Exercise(
    eid: '44',
    name: 'Leg Extensions',
    type: 'Legs',
    description: "Leg Extensions are an isolation exercise that zeroes in on the quadriceps. Using a leg extension machine, you sit with shins under the padded bar and extend your legs outward. This movement places direct tension on the quads, making it ideal for refining leg definition and strengthening the front thigh muscles.",
    sets: 4,
    repetitions: 15,
    intensity: 'Medium',
    image: 'assets/images/exercises/44.gif',
  ),
  Exercise(
    eid: '45',
    name: 'Lying Leg Curls',
    type: 'Legs',
    description: "Lying Leg Curls target the hamstrings, using a specific machine where you lie face down and curl weights upwards by flexing your knees. This isolation exercise provides focused tension on the back of the thighs, aiding in hamstring development, strength, and balance with the quadriceps.",
    sets: 4,
    repetitions: 12,
    intensity: 'Low',
    image: 'assets/images/exercises/45.gif',
  ),
  Exercise(
    eid: '46',
    name: 'Single Leg Curl',
    type: 'Legs',
    description: "The Single Leg Curl is an isolation exercise that focuses on one hamstring at a time. Using a leg curl machine, you curl the weight using one leg, ensuring concentrated muscle engagement. This unilateral movement helps identify and rectify strength imbalances between legs while promoting individual hamstring development and flexibility.",
    sets: 4,
    repetitions: 12,
    intensity: 'Low',
    image: 'assets/images/exercises/46.gif',
  ),
  Exercise(
    eid: '47',
    name: 'Seated Leg Curls',
    type: 'Legs',
    description: "The Seated Leg Curl is an isolation exercise targeting the hamstrings. Performed on a designated machine, you sit with your legs extended and pull the weight downward by bending your knees. The seated position offers a different angle of muscle engagement compared to lying leg curls, emphasizing hamstring contraction and development from another perspective.",
    sets: 4,
    repetitions: 15,
    intensity: 'Low',
    image: 'assets/images/exercises/47.gif',
  ),
  Exercise(
    eid: '48',
    name: 'Machine Adductions',
    type: 'Legs',
    description: "Machine Adductions primarily target the inner thigh muscles, or adductors. Using a leg adduction machine, you sit and place your legs on padded levers, then squeeze your thighs together against resistance. This movement strengthens and tones the inner thighs, aiding in overall leg stability and reducing the risk of injury.",
    sets: 4,
    repetitions: 12,
    intensity: 'Low',
    image: 'assets/images/exercises/48.gif',
  ),
  Exercise(
    eid: '49',
    name: 'Standing Calf Raises',
    type: 'Legs',
    description: "Standing Calf Raises focus on the gastrocnemius muscle in the calf. Performed either bodyweight or with added resistance, you raise your heels off the ground by pushing through the balls of your feet. This exercise strengthens and defines the calf muscles, enhancing lower leg aesthetics and functional strength.",
    sets: 4,
    repetitions: 15,
    intensity: 'Low',
    image: 'assets/images/exercises/49.gif',
  ),

  Exercise(
    eid: '50',
    name: 'Seated Calf Raises',
    type: 'Legs',
    description: "Seated Calf Raises target the soleus muscle, which lies beneath the gastrocnemius. Using a seated calf raise machine, you place weight on your thighs and lift your heels by pushing through the balls of your feet. This seated position isolates the soleus, providing a complementary approach to overall calf development alongside standing variations.",
    sets: 4,
    repetitions: 15,
    intensity: 'Low',
    image: 'assets/images/exercises/50.gif',
  ),
];


const List<Exercise> absWorkout = [
  Exercise(
    eid: '51',
    name: 'Crunches',
    type: 'Abs',
    description: "Crunches are a core exercise primarily focusing on the rectus abdominis, or the front abdominal muscles. Lying on the back with knees bent, you curl the upper body toward the pelvis. This movement engages the abs, aiding in core strength and muscle definition, and is a staple in many abdominal routines.",
    sets: 4,
    repetitions: 20,
    intensity: 'Low',
    image: 'assets/images/exercises/51.gif',
  ),
  Exercise(
    eid: '52',
    name: 'Sit Ups',
    type: 'Abs',
    description: "Sit-ups are a core-strengthening exercise targeting the rectus abdominis and the obliques. Starting from a lying position with bent knees and feet anchored, you lift your upper body toward the knees, engaging the entire abdominal region. Sit-ups not only enhance abdominal muscle definition but also promote functional core strength and stability.",
    sets: 4,
    repetitions: 20,
    intensity: 'Low',
    image: 'assets/images/exercises/52.gif',
  ),
  Exercise(
    eid: '53',
    name: 'Quarter Sit Ups',
    type: 'Abs',
    description: "Quarter Sit-Ups are a variation of the traditional sit-up, focusing more intently on the rectus abdominis. Starting in a lying position with knees bent, you perform a partial sit-up, lifting only a quarter of the way up. This limited range of motion maintains constant tension on the abdominal muscles, providing a more concentrated burn and engagement, ideal for targeting the upper abs and enhancing core endurance.",
    sets: 4,
    repetitions: 15,
    intensity: 'Medium',
    image: 'assets/images/exercises/53.gif',
  ),
  Exercise(
    eid: '54',
    name: 'HOW TO DO DRAGON FLAG',
    type: 'Abs',
    description: "The Dragon Flag, popularized by Bruce Lee and often associated with advanced core strength and control, primarily targets the rectus abdominis and the obliques, but it also engages stabilizing muscles throughout the body.",
    sets: 4,
    repetitions: 15,
    intensity: 'Medium',
    image: 'assets/images/exercises/54.gif',
  ),
  Exercise(
    eid: '55',
    name: 'Cross Crunches',
    type: 'Abs',
    description: "Cross Crunches target the oblique muscles while also engaging the rectus abdominis. Lying flat on your back with legs outstretched and arms extended overhead, raise one leg and the opposite arm simultaneously, trying to touch your elbow to the opposite knee. Return to the starting position and alternate sides. This diagonal motion emphasizes rotational core strength and offers a dynamic twist on traditional crunches.",
    sets: 4,
    repetitions: 15,
    intensity: 'Low',
    image: 'assets/images/exercises/55.gif',
  ),
  Exercise(
    eid: '56',
    name: 'STANDING CABLE CRUNCH',
    type: 'Abs',
    description: "The Standing Cable Crunch targets the rectus abdominis using a cable machine. Standing with your back to the machine, hold a rope attachment with both hands near your temples. Flex at the waist, drawing your elbows towards your knees while resisting the cable pull. Keep legs stationary and focus on contracting the abs. This variation challenges the core while also allowing for adjustable resistance, ensuring progression and adaptability.",
    sets: 4,
    repetitions: 15,
    intensity: 'Medium',
    image: 'assets/images/exercises/56.gif',
  ),
  Exercise(
    eid: '57',
    name: 'SEATED BENCH LEG PULL-IN',
    type: 'Abs',
    description: "The Seated Bench Leg Pull-In primarily targets the rectus abdominis. Begin by sitting on the edge of a bench, gripping the sides for stability. Lean back slightly, extending your legs out in front. Pull your knees toward your chest in a controlled motion, contracting the abs. Extend legs back out without touching the ground. This exercise provides an effective lower abdominal workout while also engaging stabilizer muscles in the core.",
    sets: 4,
    repetitions: 15,
    intensity: 'Medium',
    image: 'assets/images/exercises/57.gif',
  ),
];




const List<Exercise> shouldersWorkout = [
  Exercise(
    eid: '58',
    name: 'Back Presses',
    type: 'Shoulders',
    description: "Back Presses target the posterior deltoids, providing strength and definition to the back of the shoulder region.",
    sets: 4,
    repetitions: 10,
    intensity: 'High',
    image: 'assets/images/exercises/58.gif',
  ),
  Exercise(
    eid: '59',
    name: 'Front Presses',
    type: 'Shoulders',
    description: "Front Presses emphasize the anterior deltoids, helping in sculpting the front of the shoulder and improving pushing strength.",
    sets: 3,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/59.gif',
  ),
  Exercise(
    eid: '60',
    name: 'Bent-Over Lateral Raises',
    type: 'Shoulders',
    description: "Bent-Over Lateral Raises focus on the rear deltoids, enhancing the rounded appearance of the shoulder and aiding in shoulder stability.",
    sets: 4,
    repetitions: 15,
    intensity: 'Medium',
    image: 'assets/images/exercises/60.gif',
  ),
  Exercise(
    eid: '61',
    name: 'Lateral Dumbbell Raises',
    type: 'Shoulders',
    description: "Lateral Dumbbell Raises work on the medial deltoids, giving the shoulder its cap-like appearance and width.",
    sets: 3,
    repetitions: 12,
    intensity: 'High',
    image: 'assets/images/exercises/61.gif',
  ),
  Exercise(
    eid: '62',
    name: 'Alternate Front Arm Raises',
    type: 'Shoulders',
    description: "Alternate Front Arm Raises primarily engage the anterior deltoids, aiding in forward lifting strength and frontal shoulder definition.",
    sets: 4,
    repetitions: 10,
    intensity: 'Medium',
    image: 'assets/images/exercises/62.gif',
  ),
  Exercise(
    eid: '63',
    name: 'One Dumbbell Front Raises',
    type: 'Shoulders',
    description: "One Dumbbell Front Raises target the front shoulder muscles, offering an alternative grip and engagement from traditional front raises.",
    sets: 3,
    repetitions: 12,
    intensity: 'Low',
    image: 'assets/images/exercises/63.gif',
  ),
  Exercise(
    eid: '64',
    name: 'Upright Rows',
    type: 'Shoulders',
    description: "Upright Rows engage both the deltoids and trapezius, contributing to upper shoulder and neck strength and definition.",
    sets: 4,
    repetitions: 10,
    intensity: 'High',
    image: 'assets/images/exercises/64.gif',
  ),
  Exercise(
    eid: '65',
    name: 'Nautilus Lateral Raises',
    type: 'Shoulders',
    description: "Nautilus Lateral Raises utilize machine resistance to isolate the medial deltoids, ensuring consistent tension throughout the exercise.",
    sets: 3,
    repetitions: 15,
    intensity: 'Medium',
    image: 'assets/images/exercises/65.gif',
  ),
];


const List<Exercise> forearmsWorkout = [
  Exercise(
    eid: '66',
    name: 'Wrist Roller',
    type: 'Forearms',
    description: "The Wrist Roller is a classic tool designed to target both the flexor and extensor muscles of the forearms. Using a rolling motion, it provides consistent tension, making it an effective tool for enhancing grip strength and forearm endurance.",
    sets: 3,
    repetitions: 15,
    intensity: 'Medium',
    image: 'assets/images/exercises/66.gif',
  ),
  Exercise(
    eid: '67',
    name: 'Barbell Reverse Wrist Curl',
    type: 'Forearms',
    description: "Barbell Reverse Wrist Curl isolates the extensor muscles of the forearms. By using an overhand grip on the barbell, it targets and strengthens the upper portion of the forearms, aiding in balanced muscle development and preventing wrist injuries.",
    sets: 4,
    repetitions: 12,
    intensity: 'High',
    image: 'assets/images/exercises/67.gif',
  ),
  Exercise(
    eid: '68',
    name: 'Barbell Reverse Curl',
    type: 'Forearms',
    description: "The Barbell Reverse Curl is a dual-purpose exercise focusing on both the forearms and the brachioradialis. This curl variation not only enhances the grip strength but also promotes wrist stability and overall forearm health.",
    sets: 3,
    repetitions: 12,
    intensity: 'Medium',
    image: 'assets/images/exercises/68.gif',
  ),
  Exercise(
    eid: '69',
    name: 'Behind the Back Barbell Wrist Curl',
    type: 'Forearms',
    description: "This unique exercise, performed with the barbell behind the body, puts a concentrated emphasis on the forearm flexors. It is particularly beneficial for improving wrist flexion strength and offers a different angle of resistance for muscle growth.",
    sets: 4,
    repetitions: 10,
    intensity: 'High',
    image: 'assets/images/exercises/69.gif',
  ),
  Exercise(
    eid: '70',
    name: 'Weighted Neutral Wrist Curl',
    type: 'Forearms',
    description: "The Weighted Neutral Wrist Curl, with its neutral grip orientation, places a focus on isolating the forearm flexors. It's great for building endurance, muscle tone, and strengthening the tendons and ligaments surrounding the wrist joint.",
    sets: 3,
    repetitions: 15,
    intensity: 'Medium',
    image: 'assets/images/exercises/70.gif',
  ),
  Exercise(
    eid: '71',
    name: 'Dumbbell Seated Neutral Wrist Curl',
    type: 'Forearms',
    description: "The Dumbbell Seated Neutral Wrist Curl is performed in a seated position, offering stability and targeted engagement. With the neutral grip using dumbbells, it ensures a full range of motion, effectively targeting the forearm flexors with a focus on controlled movement.",
    sets: 4,
    repetitions: 12,
    intensity: 'High',
    image: 'assets/images/exercises/71.gif',
  ),
];


const List<Exercise> cardioWorkout = [
  Exercise(
    eid: '72',
    name: 'Riding Bicycle',
    type: 'Cardio',
    description: "Riding a bicycle offers a low-impact cardiovascular workout that is great for toning the lower body and improving cardiovascular health. Suitable for all fitness levels, cycling can be done outdoors or on stationary bikes.",
    sets: 0,
    repetitions: 0,
    intensity: 'Medium',
    image: 'assets/images/exercises/72.gif',
  ),
  Exercise(
    eid: '73',
    name: 'Walking',
    type: 'Cardio',
    description: "Walking is a foundational and low-impact aerobic exercise that benefits the cardiovascular system. It's an excellent way to get started on a fitness journey and offers flexibility in terms of pace and distance.",
    sets: 0,
    repetitions: 0,
    intensity: 'Low',
    image: 'assets/images/exercises/73.gif',
  ),
  Exercise(
    eid: '74',
      name: 'Briskly Walking',
    type: 'Cardio',
    description: "Briskly walking elevates the heart rate more than regular walking and offers more cardiovascular benefits. It's a great way to burn more calories without resorting to running.",
    sets: 0,
    repetitions: 0,
    intensity: 'Medium',
    image: 'assets/images/exercises/74.gif',
  ),
  Exercise(
    eid: '75',
    name: 'Running',
    type: 'Cardio',
    description: "Running is a high-impact aerobic exercise that strengthens the heart and lungs. It's effective for calorie burn, improving endurance, and strengthening the lower body muscles.",
    sets: 0,
    repetitions: 0,
    intensity: 'High',
    image: 'assets/images/exercises/75.gif',
  ),
  Exercise(
    eid: '76',
    name: 'Sprint',
    type: 'Cardio',
    description: "Sprinting is a short-duration, high-intensity run. It's excellent for enhancing cardiovascular strength, improving muscle tone, and boosting metabolism.",
    sets: 0,
    repetitions: 0,
    intensity: 'Very High',
    image: 'assets/images/exercises/76.gif',
  ),
  Exercise(
    eid: '77',
    name: 'Wave Walk Machine',
    type: 'Cardio',
    description: "The Wave Walk Machine offers a unique blend of walking and lateral movement, targeting different leg muscles while offering a comprehensive cardio workout.",
    sets: 0,
    repetitions: 0,
    intensity: 'Medium',
    image: 'assets/images/exercises/77.gif',
  ),
  Exercise(
    eid: '78',
    name: 'Treadmill',
    type: 'Cardio',
    description: "The Treadmill allows users to walk, jog, or run indoors. It's ideal for structured workouts and interval training, making it a versatile piece of gym equipment.",
    sets: 0,
    repetitions: 0,
    intensity: 'Variable',
    image: 'assets/images/exercises/78.gif',
  ),
  Exercise(
    eid: '79',
    name: 'Manual Treadmill',
    type: 'Cardio',
    description: "The Manual Treadmill is powered by the user's movement. It requires more effort than a motorized version, offering a more challenging workout.",
    sets: 0,
    repetitions: 0,
    intensity: 'High',
    image: 'assets/images/exercises/79.gif',
  ),
  Exercise(
    eid: '80',
    name: 'Elliptical Machine',
    type: 'Cardio',
    description: "The Elliptical Machine provides a low-impact, full-body workout. With its smooth motion, it's particularly beneficial for those looking for joint-friendly cardio exercises.",
    sets: 0,
    repetitions: 0,
    intensity: 'Medium',
    image: 'assets/images/exercises/80.gif',
  ),
  Exercise(
    eid: '81',
    name: 'Stair Climber Machine',
    type: 'Cardio',
    description: "The Stair Climber simulates the action of climbing stairs. It offers an intense lower-body workout while providing excellent cardiovascular benefits.",
    sets: 0,
    repetitions: 0,
    intensity: 'High',
    image: 'assets/images/exercises/81.gif',
  ),
];
